#!/usr/bin/env python
import argparse
import json

from telethon import TelegramClient, functions, types

from ArgsParser import ArgsParser

with open('secret/telegram-planner.json') as f:
    secret_values = json.load(f)

client = TelegramClient('anon', secret_values['api_id'], secret_values['api_hash'])

def create_parser():
    parser = argparse.ArgumentParser()

    parser.add_argument('action')
    parser.add_argument('subaction')
    parser.add_argument('--channel', dest='channel', required=False, default=None,
        help='Name of the channel to be used')
    parser.add_argument('--text-path', dest='text_path', required=False, default=None,
        help='File where the text of the message to be scheduled is')
    parser.add_argument('--datetime', dest='datetime', required=False, default=None,
        help='Datetime for publishing the post (format YYYYMMDD-HHMM)')

    return parser

args_parser = ArgsParser(client, secret_values['posts_path'])
parser = create_parser()
args = parser.parse_args()

async def main():
    await args_parser.process_actions(args)

with client:
    client.loop.run_until_complete(main())
